# DataFrame

### DataFrame can be created in 3 ways:

#### 1. Lists --> dataframe
#### 2. Dictionary --> dataframe
#### 3. read_csv --> dataframe

In [1]:
## Dataframe --> combination of Rows and Columns --> 2D Data Structure

rows=[[1,2,3,4],[5,6,7,8],[9,0,1,2],[4,3,2,1]]

In [2]:
import pandas as pd

In [3]:
list_data = pd.DataFrame(rows,columns=['a','b','c','d'])

In [4]:
print(list_data)

   a  b  c  d
0  1  2  3  4
1  5  6  7  8
2  9  0  1  2
3  4  3  2  1

In [5]:
list_data.shape

(4, 4)

In [6]:
## Dictionary --> Dataframe
## Dictionary --> Dataframe --> rows and columns combination
dict_data = {'Name':['Amit','Yash','Vivek'],'Money':[1,5,6],'Financial_Stress':[1,1,0]}

In [7]:
dict_dataframe=pd.DataFrame(dict_data)

In [8]:
print(dict_dataframe)

    Name  Money  Financial_Stress
0   Amit      1                 1
1   Yash      5                 1
2  Vivek      6                 0

In [9]:
import pandas as pd
data = pd.read_csv('Student Depression Dataset.csv')

In [10]:
data

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [11]:
type(data)

pandas.DataFrame

In [12]:
df = pd.read_csv('Student Depression Dataset.csv')

In [13]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [14]:
## Data Exploration --> Attributes & Functions for the dataframe

## Attributes

#### 1. shape --> it provides the info about the (row,column) information about the dataset 
##### syntax --> df.shape

In [15]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [16]:
df.shape

(27901, 18)

#### 2. dtypes --> It provides the idea about the datatype of all columns, so all cloumn with their name and their associated data type will be shown by using dtypes
##### syntax --> df.dtypes

In [17]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [18]:
df.dtypes

id                                         int64
Gender                                       str
Age                                      float64
City                                         str
Profession                                   str
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                               str
Dietary Habits                               str
Degree                                       str
Have you ever had suicidal thoughts ?        str
Work/Study Hours                         float64
Financial Stress                         float64
Family History of Mental Illness             str
Depression                                 int64
dtype: object

#### 3. index --> for a Dataframe with labelled index we can get the idea about the label just by using index attribute

In [19]:
df.index

RangeIndex(start=0, stop=27901, step=1)

#### 4. columns --> it provides the idea about all of the column names of the given dataframe

In [20]:
df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

#### 5. values --> it provides the idea about the values present row by row inside the dataframe

In [21]:
df.values

array([[2, 'Male', 33.0, ..., 1.0, 'No', 1],
       [8, 'Female', 24.0, ..., 2.0, 'Yes', 0],
       [26, 'Male', 31.0, ..., 1.0, 'Yes', 0],
       ...,
       [140689, 'Male', 31.0, ..., 2.0, 'No', 0],
       [140690, 'Female', 18.0, ..., 5.0, 'No', 1],
       [140699, 'Male', 27.0, ..., 3.0, 'Yes', 1]],
      shape=(27901, 18), dtype=object)

In [22]:
df.values[0]

array([2, 'Male', 33.0, 'Visakhapatnam', 'Student', 5.0, 0.0, 8.97, 2.0,
       0.0, '5-6 hours', 'Healthy', 'B.Pharm', 'Yes', 3.0, 1.0, 'No', 1],
      dtype=object)

#### 6. ndim --> it provides the idea about the dimention of the dataframe

In [23]:
df.ndim

2

#### 7. size --> Total number of elements present inside the detaframe, that means all rows * all columns (column 3 --? 50 rows, column 2 --> 50 rows, column 3 --> 70 rows --> size --> 50+50+70 )

In [24]:
df.size

502218

## Functions

#### 1. head() --> to get to have the idea about the data that your detaset is storing as the top 5, that means that starting from the top we can get the top 5 rows and along with that if 1 want that instead of top 5 rows i want to see a fixed no. of rows from the rows , that number i can pass inside the head() as a parameter

In [25]:
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

In [26]:
df.head(3)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0

In [27]:
df.head(13)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,Less than 5 hours,Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,Less than 5 hours,Unhealthy,Class 12,No,0.0,1.0,Yes,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
10,83,Male,24.0,Nagpur,Student,3.0,0.0,6.10,3.0,0.0,5-6 hours,Moderate,Class 12,Yes,11.0,1.0,Yes,1
11,91,Male,33.0,Vadodara,Student,3.0,0.0,7.03,4.0,0.0,Less than 5 hours,Healthy,BE,Yes,10.0,2.0,Yes,0
12,94,Male,27.0,Kalyan,Student,5.0,0.0,7.04,1.0,0.0,Less than 5 hours,Moderate,M.Tech,No,10.0,1.0,Yes,1

#### 2. tail() --> provide the insight about the dataframe from the bottom so tail() can show us the bottom 5 rows and again based on the value you will be passing as the parameter, these many values you can get using the tail fn ()

In [28]:
df.tail()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [29]:
df.tail(1)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [30]:
df.tail(13)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
27888,140630,Male,19.0,Kolkata,Student,4.0,0.0,7.13,1.0,0.0,More than 8 hours,Moderate,Class 12,No,10.0,2.0,No,1
27889,140631,Male,33.0,Ahmedabad,Student,1.0,0.0,5.70,2.0,0.0,Less than 5 hours,Healthy,MCA,Yes,2.0,2.0,No,0
27890,140635,Male,28.0,Ludhiana,Student,3.0,0.0,5.03,3.0,0.0,Less than 5 hours,Moderate,Class 12,Yes,6.0,2.0,Yes,0
27891,140645,Female,28.0,Thane,Student,4.0,0.0,7.77,3.0,0.0,Less than 5 hours,Unhealthy,MSc,No,2.0,5.0,No,1
27892,140669,Female,20.0,Indore,Student,3.0,0.0,7.72,5.0,0.0,Less than 5 hours,Moderate,Class 12,Yes,8.0,1.0,No,0
27893,140672,Female,24.0,Hyderabad,Student,3.0,0.0,6.02,2.0,0.0,7-8 hours,Moderate,B.Arch,No,8.0,2.0,No,0
27894,140681,Male,23.0,Srinagar,Student,3.0,0.0,6.00,2.0,0.0,More than 8 hours,Healthy,MBBS,Yes,12.0,4.0,No,0
27895,140684,Male,31.0,Lucknow,Student,2.0,0.0,7.27,5.0,0.0,7-8 hours,Moderate,B.Com,Yes,6.0,1.0,Yes,0
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

#### 3. sample() --> provides the insight about the dataframe as the random values present inside the dataset and again based on how many values i want i ccan put the parameter as per that .

In [31]:
df.sample()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
214,1049,Male,20.0,Ludhiana,Student,3.0,0.0,5.67,2.0,0.0,More than 8 hours,Unhealthy,Class 12,Yes,12.0,5.0,No,1

In [32]:
df.sample(5)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
486,2486,Male,29.0,Surat,Student,4.0,0.0,8.04,5.0,0.0,More than 8 hours,Unhealthy,ME,No,1.0,2.0,Yes,0
5566,28060,Male,20.0,Nashik,Student,1.0,0.0,7.17,1.0,0.0,Less than 5 hours,Unhealthy,Class 12,Yes,5.0,4.0,Yes,1
9473,47781,Male,34.0,Lucknow,Student,2.0,0.0,6.78,3.0,0.0,More than 8 hours,Healthy,B.Com,Yes,12.0,4.0,No,0
16574,83817,Male,24.0,Thane,Student,5.0,0.0,8.62,2.0,0.0,5-6 hours,Moderate,B.Pharm,Yes,10.0,1.0,No,1
1469,7583,Female,28.0,Srinagar,Student,4.0,0.0,6.86,1.0,0.0,7-8 hours,Unhealthy,BHM,Yes,3.0,4.0,No,1

#### 4. info() --> info() provides the idea 
##### a. about the datatype of all columns
##### b. Number of missing values of all columns
##### c. Dataframe storage in memory

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27898 non-null  float64
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
dtypes: float64(8), int64(2), str(8)
memory usage: 5.2 MB

#### 5. describe() --> it provides an idea as the mathematical summary of the data --> minimum,maximum,count,mean,std,25%,50%,75%

In [34]:
df.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress,Depression
count,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27898.000000,27901.000000
mean,70442.149421,25.822300,3.141214,0.000430,7.656104,2.943837,0.000681,7.156984,3.139867,0.585499
std,40641.175216,4.905687,1.381465,0.043992,1.470707,1.361148,0.044394,3.707642,1.437347,0.492645
min,2.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,35039.000000,21.000000,2.000000,0.000000,6.290000,2.000000,0.000000,4.000000,2.000000,0.000000
50%,70684.000000,25.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,3.000000,1.000000
75%,105818.000000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,4.000000,1.000000
max,140699.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,5.000000,1.000000

In [35]:
## before data cleaning , we must have the idea that whether if the data is having any missing value or not or any duplicate value or not

In [36]:
## Missing value or not --> isnull()

In [37]:
df.isnull().sum()

id                                       0
Gender                                   0
Age                                      0
City                                     0
Profession                               0
Academic Pressure                        0
Work Pressure                            0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Degree                                   0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         3
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [38]:
data={'name':['Neel','Shashi','Ravi','Nishant'],'Package':[5,6,3,9],'Degree':['Bca','12th','Bca',None]}

In [39]:
pd.DataFrame(data)

      name  Package Degree
0     Neel        5    Bca
1   Shashi        6   12th
2     Ravi        3    Bca
3  Nishant        9    NaN

In [40]:
pd.DataFrame(data).isnull().sum()

name       0
Package    0
Degree     1
dtype: int64

In [41]:
## missing values --> nan vlaues in the dataset

In [42]:
## duplicate values are present or not --> duplicated()

In [43]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
27896    False
27897    False
27898    False
27899    False
27900    False
Length: 27901, dtype: bool

In [44]:
df.duplicated().sum()

np.int64(0)

## data cleaning
#### 1. Missing Values
#### 2. Duplicate
#### 3. Renaming the column as will

In [45]:
df.rename(columns={'CGPA':'Cgpa'})

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,Cgpa,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [46]:
df.rename(columns={'Age':'Student_age','Gender':'Studend_Gender'})

,id,Studend_Gender,Student_age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [47]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [48]:
## In order to make sure that the changes are going to be permanent we can go with inplace parameter

In [49]:
df.rename(columns={'Age':'AGE'},inplace=True)

In [50]:
df

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

## Mathematical Functions in Datafram

#### 1. sum() --> it calculates the sum of all values present in a column or in multiple columns
#### 2. mean() --> it calculates the average of all values or mean of all values in a column
#### 3. min() --> it calculates the minimum vlaues of a column
#### 4. max() --> it calculates the maximum value of a column
#### 5. median() --> it calculates the median value of a column
#### 6. var() --> it calculates the variance of all values of a column

### axis --> it helps us calculate the mathematical calculation row wise or column wise
####  mathmatical Operation --> row wise ---> axis = 1
#### mathematical operation --> column wise --> axis = 0

### 1. sum()

In [52]:
# sum()
df.sum()

id                                                                              1965406411
Gender                                   MaleFemaleMaleFemaleFemaleMaleMaleFemaleMaleMa...
AGE                                                                               720468.0
City                                     VisakhapatnamBangaloreSrinagarVaranasiJaipurPu...
Profession                               StudentStudentStudentStudentStudentStudentStud...
Academic Pressure                                                                  87643.0
Work Pressure                                                                         12.0
CGPA                                                                           213612.9625
Study Satisfaction                                                                 82136.0
Job Satisfaction                                                                      19.0
Sleep Duration                           5-6 hours5-6 hoursLess than 5 hours7-8 hours5-...
Dietary Habits                           HealthyModerateHealthyModerateModerateHealthyH...
Degree                                   B.PharmBScBABCAM.TechPhDBScClass 12B.EdLLBClas...
Have you ever had suicidal thoughts ?    YesNoNoYesYesNoNoNoYesYesYesYesNoNoYesYesYesYe...
Work/Study Hours                                                                  199687.0
Financial Stress                                                                   87596.0
Family History of Mental Illness         NoYesYesYesNoNoNoYesNoNoYesYesYesYesYesYesYesN...
Depression                                                                           16336
dtype: object

In [53]:

df.values[0]

array([2, 'Male', 33.0, 'Visakhapatnam', 'Student', 5.0, 0.0, 8.97, 2.0,
       0.0, '5-6 hours', 'Healthy', 'B.Pharm', 'Yes', 3.0, 1.0, 'No', 1],
      dtype=object)

In [54]:
df.sum(axis=1)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [55]:
df.sum(axis=0)

id                                                                              1965406411
Gender                                   MaleFemaleMaleFemaleFemaleMaleMaleFemaleMaleMa...
AGE                                                                               720468.0
City                                     VisakhapatnamBangaloreSrinagarVaranasiJaipurPu...
Profession                               StudentStudentStudentStudentStudentStudentStud...
Academic Pressure                                                                  87643.0
Work Pressure                                                                         12.0
CGPA                                                                           213612.9625
Study Satisfaction                                                                 82136.0
Job Satisfaction                                                                      19.0
Sleep Duration                           5-6 hours5-6 hoursLess than 5 hours7-8 hours5-...
Dietary Habits                           HealthyModerateHealthyModerateModerateHealthyH...
Degree                                   B.PharmBScBABCAM.TechPhDBScClass 12B.EdLLBClas...
Have you ever had suicidal thoughts ?    YesNoNoYesYesNoNoNoYesYesYesYesNoNoYesYesYesYe...
Work/Study Hours                                                                  199687.0
Financial Stress                                                                   87596.0
Family History of Mental Illness         NoYesYesYesNoNoNoYesNoNoYesYesYesYesYesYesYesN...
Depression                                                                           16336
dtype: object

### 2. mean()

In [56]:
df.mean()

TypeError: Cannot perform reduction 'mean' with string dtype

### 3. min()

In [57]:
df.min()

id                                               2
Gender                                      Female
AGE                                           18.0
City                                           3.0
Profession                               Architect
Academic Pressure                              0.0
Work Pressure                                  0.0
CGPA                                           0.0
Study Satisfaction                             0.0
Job Satisfaction                               0.0
Sleep Duration                           5-6 hours
Dietary Habits                             Healthy
Degree                                      B.Arch
Have you ever had suicidal thoughts ?           No
Work/Study Hours                               0.0
Financial Stress                               1.0
Family History of Mental Illness                No
Depression                                       0
dtype: object

### 4. max()

In [58]:
df.max()

id                                               140699
Gender                                             Male
AGE                                                59.0
City                                      Visakhapatnam
Profession                               UX/UI Designer
Academic Pressure                                   5.0
Work Pressure                                       5.0
CGPA                                               10.0
Study Satisfaction                                  5.0
Job Satisfaction                                    4.0
Sleep Duration                                   Others
Dietary Habits                                Unhealthy
Degree                                              PhD
Have you ever had suicidal thoughts ?               Yes
Work/Study Hours                                   12.0
Financial Stress                                    5.0
Family History of Mental Illness                    Yes
Depression                                            1
dtype: object

### 5. median()

In [60]:
df.sample(5)

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
22132,111765,Male,26.0,Visakhapatnam,Student,2.0,0.0,8.25,4.0,0.0,7-8 hours,Healthy,BA,Yes,11.0,2.0,Yes,0
12918,65395,Male,21.0,Kalyan,Student,5.0,0.0,6.86,3.0,0.0,Less than 5 hours,Moderate,MSc,Yes,2.0,2.0,Yes,1
9235,46581,Female,26.0,Srinagar,Student,3.0,0.0,6.59,1.0,0.0,Less than 5 hours,Moderate,BHM,Yes,10.0,3.0,No,1
10695,54149,Female,28.0,Ludhiana,Student,2.0,0.0,7.71,1.0,0.0,More than 8 hours,Moderate,M.Com,Yes,2.0,4.0,No,0
24704,124458,Male,21.0,Agra,Student,3.0,0.0,7.77,4.0,0.0,7-8 hours,Unhealthy,B.Com,Yes,2.0,5.0,Yes,1

### 6. var()

In [69]:
df.var()

TypeError: Cannot perform reduction 'var' with string dtype

In [61]:
df.columns

Index(['id', 'Gender', 'AGE', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [64]:
## for selecting a column from a dataframe --> df['column name']
## for selecting Multiple columns from a dataframe --> df[['col1','col2','col3',.......]]

In [62]:
df['Academic Pressure']

0        5.0
1        2.0
2        3.0
3        3.0
4        4.0
        ...
27896    5.0
27897    2.0
27898    3.0
27899    5.0
27900    4.0
Name: Academic Pressure, Length: 27901, dtype: float64

In [67]:
data = df[['AGE','Sleep Duration','Dietary Habits','Work/Study Hours','Financial Stress']]

In [68]:
data

,AGE,Sleep Duration,Dietary Habits,Work/Study Hours,Financial Stress
0,33.0,5-6 hours,Healthy,3.0,1.0
1,24.0,5-6 hours,Moderate,3.0,2.0
2,31.0,Less than 5 hours,Healthy,9.0,1.0
3,28.0,7-8 hours,Moderate,4.0,5.0
4,25.0,5-6 hours,Moderate,1.0,1.0
...,...,...,...,...,...
27896,27.0,5-6 hours,Unhealthy,7.0,1.0
27897,27.0,Less than 5 hours,Healthy,0.0,3.0
27898,31.0,5-6 hours,Unhealthy,12.0,2.0
27899,18.0,Less than 5 hours,Healthy,10.0,5.0
27900,27.0,Less than 5 hours,Healthy,2.0,3.0

## select the specific rows of our dataframe --> loc[] and iloc[]

#### loc[] --> location --> it fetches the record as per the labelled index location of the value
#### ilog[] --> integer location --> it fetches the record as par the integer index location

In [70]:
df.head(2)

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0

In [71]:
df.loc[10]

id                                              83
Gender                                        Male
AGE                                           24.0
City                                        Nagpur
Profession                                 Student
Academic Pressure                              3.0
Work Pressure                                  0.0
CGPA                                           6.1
Study Satisfaction                             3.0
Job Satisfaction                               0.0
Sleep Duration                           5-6 hours
Dietary Habits                            Moderate
Degree                                    Class 12
Have you ever had suicidal thoughts ?          Yes
Work/Study Hours                              11.0
Financial Stress                               1.0
Family History of Mental Illness               Yes
Depression                                       1
Name: 10, dtype: object

In [73]:
df.iloc[1000]

id                                                5152
Gender                                            Male
AGE                                               29.0
City                                     Visakhapatnam
Profession                                     Student
Academic Pressure                                  3.0
Work Pressure                                      0.0
CGPA                                              7.94
Study Satisfaction                                 3.0
Job Satisfaction                                   0.0
Sleep Duration                               5-6 hours
Dietary Habits                                Moderate
Degree                                             BSc
Have you ever had suicidal thoughts ?               No
Work/Study Hours                                   2.0
Financial Stress                                   1.0
Family History of Mental Illness                   Yes
Depression                                           0
Name: 1000, dtype: object

In [74]:
df.iloc[0:11]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,Less than 5 hours,Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,Less than 5 hours,Unhealthy,Class 12,No,0.0,1.0,Yes,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
10,83,Male,24.0,Nagpur,Student,3.0,0.0,6.10,3.0,0.0,5-6 hours,Moderate,Class 12,Yes,11.0,1.0,Yes,1

In [75]:
## fetch the record starting from index 8 to all of the records

In [76]:
df.iloc[8:]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
10,83,Male,24.0,Nagpur,Student,3.0,0.0,6.10,3.0,0.0,5-6 hours,Moderate,Class 12,Yes,11.0,1.0,Yes,1
11,91,Male,33.0,Vadodara,Student,3.0,0.0,7.03,4.0,0.0,Less than 5 hours,Healthy,BE,Yes,10.0,2.0,Yes,0
12,94,Male,27.0,Kalyan,Student,5.0,0.0,7.04,1.0,0.0,Less than 5 hours,Moderate,M.Tech,No,10.0,1.0,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [77]:
## slicing with skipping values
df[::2]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27892,140669,Female,20.0,Indore,Student,3.0,0.0,7.72,5.0,0.0,Less than 5 hours,Moderate,Class 12,Yes,8.0,1.0,No,0
27894,140681,Male,23.0,Srinagar,Student,3.0,0.0,6.00,2.0,0.0,More than 8 hours,Healthy,MBBS,Yes,12.0,4.0,No,0
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [78]:
## loc[] --> location of hte giving index

In [79]:
data = {'name':['Neel','Shashi','Ravi'],'Age':[23,17,23],'Package':[6,5,4]}

In [80]:
## set_index() --> it can help you out with setting a specific column as the index of the dataframe

In [81]:
data = pd.DataFrame(data)

In [83]:
data

     name  Age  Package
0    Neel   23        6
1  Shashi   17        5
2    Ravi   23        4

In [84]:
data.set_index('name')

        Age  Package
name
Neel     23        6
Shashi   17        5
Ravi     23        4

In [86]:
data = data.set_index('name')

In [87]:
data.loc['Neel']

Age        23
Package     6
Name: Neel, dtype: int64

In [88]:
## fancy indexing is possible in feching records

In [90]:
df.iloc[[1,4,6,9,15,23]]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
15,106,Male,29.0,Srinagar,Student,3.0,0.0,8.58,3.0,0.0,More than 8 hours,Moderate,M.Tech,Yes,10.0,2.0,Yes,1
23,172,Male,23.0,Thane,Student,1.0,0.0,8.59,4.0,0.0,7-8 hours,Healthy,BHM,No,11.0,3.0,No,0

In [91]:
data

        Age  Package
name
Neel     23        6
Shashi   17        5
Ravi     23        4

In [92]:
data.loc[['Neel','Shashi']]

        Age  Package
name
Neel     23        6
Shashi   17        5

In [94]:
data.loc['Neel':]

        Age  Package
name
Neel     23        6
Shashi   17        5
Ravi     23        4

In [95]:
data.loc['Neel'::2]

      Age  Package
name
Neel   23        6
Ravi   23        4

In [96]:
## index , at the end the labelled index is else going to have integer indexing only by python

In [97]:
data

        Age  Package
name
Neel     23        6
Shashi   17        5
Ravi     23        4

In [98]:
'''data --> Neel --> 0
        --> Shashi --> 1
        --> Ravi --> 2
'''

'data --> Neel --> 0\n        --> Shashi --> 1\n        --> Ravi --> 2\n'

In [99]:
## fetching specific rows and columns

In [100]:
## df[row_1:row_n,col_1:col_n]

In [101]:
df.columns

Index(['id', 'Gender', 'AGE', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [102]:
df.loc[0:5,['Gender','City', 'Sleep Duration','Dietary Habits']]

   Gender           City     Sleep Duration Dietary Habits
0    Male  Visakhapatnam          5-6 hours        Healthy
1  Female      Bangalore          5-6 hours       Moderate
2    Male       Srinagar  Less than 5 hours        Healthy
3  Female       Varanasi          7-8 hours       Moderate
4  Female         Jaipur          5-6 hours       Moderate
5    Male           Pune  Less than 5 hours        Healthy

In [104]:
df.iloc[0:9,0:7]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0
1,8,Female,24.0,Bangalore,Student,2.0,0.0
2,26,Male,31.0,Srinagar,Student,3.0,0.0
3,30,Female,28.0,Varanasi,Student,3.0,0.0
4,32,Female,25.0,Jaipur,Student,4.0,0.0
5,33,Male,29.0,Pune,Student,2.0,0.0
6,52,Male,30.0,Thane,Student,3.0,0.0
7,56,Female,30.0,Chennai,Student,2.0,0.0
8,59,Male,28.0,Nagpur,Student,3.0,0.0